tap "homebrew/bundle"
tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "bats-core"
brew "coreutils"
brew "stow"
brew "thefuck"
brew "zellij"
brew "powerlevel10k"
#brew "lotyp/formulae/dockutil"
# # fs/network
#brew "topgrade"
brew "bat"
# brew "croc"
# brew "httpie"
# brew "ssh-copy-id"
# brew "tree"
# brew "unar"
# brew "wget"
# brew "zoxide"
#
# # search/grep/diff
# brew "fd"
brew "fzf"
# brew "git-delta"
# brew "gnu-sed"
# brew "grep"
# brew "jq"
# brew "psgrep"
# brew "ripgrep"
# brew "the_silver_searcher"
#
# # languages/tools
# brew "gh"
# brew "n"
# brew "python"
# brew "shellcheck"
#
# # media
# brew "ffmpeg"
# brew "imagemagick"
# brew "uni"
# brew "webp"
#
# # misc
# brew "grip"